-- Add visual/enriched metadata from the Objects + Enriched Data spec and
-- normalize attribute ordering for Attio-style object settings.

WITH attrs(slug, key, name, attribute_type, source, is_system, is_enriched, is_relationship, is_required, is_unique, is_editable, sort_order) AS (
  VALUES
    ('people','name','Name','Text','system',true,false,false,true,false,true,10),
    ('people','email','Email addresses','Email','system',true,false,false,false,true,true,20),
    ('people','company','Company','Relationship','relationship',false,false,true,false,false,true,30),
    ('people','job_title','Job title','Text','enriched',false,true,false,false,false,true,40),
    ('people','phone_numbers','Phone numbers','Phone','system',true,false,false,false,false,true,50),
    ('people','owner','Owner','User','system',true,false,false,false,false,true,60),
    ('people','profile_picture_url','Profile picture','URL','enriched',false,true,false,false,false,true,70),
    ('people','description','Description','Text','enriched',false,true,false,false,false,true,80),
    ('people','location','Primary location','Location','enriched',false,true,false,false,false,true,90),
    ('people','facebook_url','Facebook','URL','enriched',false,true,false,false,false,true,100),
    ('people','linkedin_url','LinkedIn','URL','enriched',false,true,false,false,false,true,110),
    ('people','twitter_url','Twitter','URL','enriched',false,true,false,false,false,true,120),
    ('people','angellist_url','AngelList','URL','enriched',false,true,false,false,false,true,130),
    ('people','instagram_url','Instagram','URL','custom',false,false,false,false,false,true,140),
    ('people','employee_range','Employee range','Number','enriched',false,true,false,false,false,true,150),
    ('people','twitter_follower_count','Twitter follower count','Number','enriched',false,true,false,false,false,true,160),
    ('people','first_interaction','First interaction','Interaction','enriched',false,true,false,false,false,false,170),
    ('people','last_interaction_at','Last interaction','Timestamp','enriched',false,true,false,false,false,false,180),
    ('people','next_interaction','Next interaction','Interaction','enriched',false,true,false,false,false,false,190),
    ('people','connection_strength','Connection strength','Number','enriched',false,true,false,false,false,false,200),
    ('people','strongest_connection','Strongest connection','User','enriched',false,true,false,false,false,false,210),
    ('people','associated_deals','Associated deals','Relationship','relationship',false,false,true,false,false,true,220),
    ('people','associated_companies','Associated companies','Relationship','relationship',false,false,true,false,false,true,230),
    ('people','associated_users','Associated users','Relationship','relationship',false,false,true,false,false,true,240),
    ('people','associated_workspaces','Associated workspaces','Relationship','relationship',false,false,true,false,false,true,250),

    ('companies','name','Name','Text','enriched',true,true,false,true,false,true,10),
    ('companies','domain','Domains','Domain','system',true,false,false,false,true,true,20),
    ('companies','team','Team','Relationship','relationship',false,true,true,false,false,true,30),
    ('companies','logo_url','Logo','URL','enriched',false,true,false,false,false,true,40),
    ('companies','description','Description','Text','enriched',false,true,false,false,false,true,50),
    ('companies','sector','Categories','Multi-select','enriched',false,true,false,false,false,true,60),
    ('companies','hq_location','Primary location','Location','enriched',false,true,false,false,false,true,70),
    ('companies','facebook_url','Facebook','URL','enriched',false,true,false,false,false,true,80),
    ('companies','linkedin_url','LinkedIn','URL','enriched',false,true,false,false,false,true,90),
    ('companies','twitter_url','Twitter','URL','enriched',false,true,false,false,false,true,100),
    ('companies','angellist_url','AngelList','URL','enriched',false,true,false,false,false,true,110),
    ('companies','instagram_url','Instagram','URL','custom',false,false,false,false,false,true,120),
    ('companies','twitter_follower_count','Twitter follower count','Number','enriched',false,true,false,false,false,true,130),
    ('companies','estimated_arr','Estimated ARR','Currency','enriched',false,true,false,false,false,false,140),
    ('companies','funding_raised','Funding raised','Currency','enriched',false,true,false,false,false,true,150),
    ('companies','founded_year','Foundation date','Date','enriched',false,true,false,false,false,true,160),
    ('companies','employees_count','Employee range','Number','enriched',false,true,false,false,false,true,170),
    ('companies','first_interaction','First interaction','Interaction','enriched',false,true,false,false,false,false,180),
    ('companies','last_interaction','Last interaction','Interaction','enriched',false,true,false,false,false,false,190),
    ('companies','next_interaction','Next interaction','Interaction','enriched',false,true,false,false,false,false,200),
    ('companies','connection_strength','Connection strength','Number','enriched',false,true,false,false,false,false,210),
    ('companies','strongest_connection','Strongest connection','User','enriched',false,true,false,false,false,false,220),
    ('companies','associated_deals','Associated deals','Relationship','relationship',false,false,true,false,false,true,230),
    ('companies','associated_workspaces','Associated workspaces','Relationship','relationship',false,false,true,false,false,true,240)
)
INSERT INTO public.crm_attributes (
  user_id,
  object_id,
  key,
  name,
  attribute_type,
  scope,
  source,
  is_system,
  is_enriched,
  is_relationship,
  is_required,
  is_unique,
  is_editable,
  sort_order
)
SELECT
  o.user_id,
  o.id,
  a.key,
  a.name,
  a.attribute_type,
  CASE WHEN a.is_system THEN 'system' ELSE 'object' END,
  a.source,
  a.is_system,
  a.is_enriched,
  a.is_relationship,
  a.is_required,
  a.is_unique,
  a.is_editable,
  a.sort_order
FROM public.crm_objects o
JOIN attrs a ON a.slug = o.slug
WHERE o.object_type = 'standard'
ON CONFLICT (object_id, key) DO UPDATE SET
  name = EXCLUDED.name,
  attribute_type = EXCLUDED.attribute_type,
  scope = EXCLUDED.scope,
  source = EXCLUDED.source,
  is_system = EXCLUDED.is_system,
  is_enriched = EXCLUDED.is_enriched,
  is_relationship = EXCLUDED.is_relationship,
  is_required = EXCLUDED.is_required,
  is_unique = EXCLUDED.is_unique,
  is_editable = EXCLUDED.is_editable,
  sort_order = EXCLUDED.sort_order;
